# Generated by Django 2.2.2 on 2019-06-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('month', models.TextField(default='-')),
                ('name', models.TextField(default='-')),
                ('incomeChannel', models.TextField(default='-')),
                ('incomeAmount', models.TextField(default='-')),
                ('incomeDate', models.TextField(default='-')),
                ('debtName', models.TextField(default='-')),
                ('debtChannel', models.TextField(default='-')),
                ('debtAmount', models.TextField(default='-')),
                ('repayDate', models.TextField(default='-')),
                ('isRepay', models.TextField(default='-')),
            ],
        ),
    ]
