# Generated by Django 2.2.2 on 2019-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190607_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField(default='-')),
                ('star', models.TextField(default='-')),
                ('ispass', models.TextField(default='-')),
                ('sort', models.TextField(default='-')),
                ('fatherSort', models.TextField(default='-')),
            ],
        ),
    ]
