# Generated by Django 2.2.2 on 2019-06-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='description',
        ),
        migrations.AddField(
            model_name='todo',
            name='debtAmount',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='debtChannel',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='incomeAmount',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='incomeChannel',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='incomeDate',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='isRepay',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='month',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.TextField(default='0'),
        ),
        migrations.AddField(
            model_name='todo',
            name='repayDate',
            field=models.TextField(default='0'),
        ),
    ]
