# Generated by Django 2.2.2 on 2019-06-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20190606_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='debtAmount',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='debtChannel',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='incomeAmount',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='incomeChannel',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='incomeDate',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='isRepay',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='month',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.TextField(default='-'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='repayDate',
            field=models.TextField(default='-'),
        ),
    ]
