# Generated by Django 2.2.2 on 2019-06-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_auto_20190607_2054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
